# --- Experiment Configuration ---

# General settings
model_config: 'RESNET'      # Options: 'CIFAR10', 'MNIST', 'LLM', 'RESNET'
dataset_name: 'CIFAR10' # The dataset to use ('CIFAR10', 'MNIST', or 'LLM')
model_dir: 'src/pretrained_models' # Directory to save/load models
log_file: 'simulation.log' # Path for the log file. Set to null or remove to disable file logging.
precision_config: '32'    # Options: '16' (mixed), '32' (standard), '64' (double)
num_generations: 2        # Number of evolutionary cycles to run
population_size: 10       # Number of models in the population

# --- Evolutionary Algorithm Settings ---
merge_strategy: 'sequential_constructive' # Options: 'average', 'fitness_weighted', 'layer-wise', 'sequential_constructive'
mutation_rate: 0.05                       # Probability of a weight being mutated
initial_mutation_strength: 0.1            # Initial strength of mutations
mutation_decay_factor: 0.9                # Factor by which mutation strength decays each generation

# --- Data Settings ---
subset_percentage: 0.1    # Percentage of the dataset to use (1.0 for full dataset)
validation_split: 0.1     # Proportion of training data to use for validation

# --- Training Epochs ---
# Default epochs used for most models.
default_epochs:
  specialize: 2
  finetune: 3

# Epochs for specific models that require different training times.
model_specific_epochs:
  LLM:
    specialize: 1
    finetune: 1
  RESNET:
    specialize: 1
    finetune: 2

# --- Dataset Settings ---
dataset_configs:
  CIFAR10:
    num_classes: 10
  MNIST:
    num_classes: 10
  LLM:
    num_classes: 77 # For banking77
  IMAGENET:
    num_classes: 1000